name: Run Unit Tests and Pylint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Analysing the code with pylint
        run: |
          poetry run pylint ./src
        continue-on-error: true
      - name: Test with pytest
        run: |
          poetry run coverage run -m pytest tests/unit -v -s
      - name: Generate Coverage Report
        run: |  
          poetry run coverage report -m
